language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
sudo: false
services:
  - docker
env:
  global:
    - PINS="arp:. arp-mirage:. mirage-vnetif:git+https://github.com/hannesm/mirage-vnetif.git#easy ethernet:git+https://github.com/hannesm/ethernet.git#easy mirage-random-test:git+https://github.com/hannesm/mirage-random-test.git#easy"
    - DISTRO=alpine
    - TESTS=true
  matrix:
    - OCAML_VERSION=4.06 PACKAGE="arp-mirage"
    - OCAML_VERSION=4.07 PACKAGE="arp"
    - OCAML_VERSION=4.08 PACKAGE="arp" DEPOPTS="arp-mirage"
    - OCAML_VERSION=4.09 PACKAGE="arp-mirage"
notifications:
  email: false
